### ISSUE TITLE
No sitemap is created. Help.

### ISSUE THREAD

**Issue by todaynogada** [benoitdemaegdt/nuxt3-sitemap#2]
No sitemap is created. Help.

node 16.14.2
npm 8.5.0
nuxtjs3 latest

**Comment by benoitdemaegdt** [comment]
Hey 👋 

Thank you for creating this issue.
Indeed, it seems that that the latest Nuxt3 release broke the sitemap generation 😞 

I'll investigate that as soon as possible.

**Comment by todaynogada** [comment]
thank you

**Comment by benoitdemaegdt** [comment]
This is because `nitro:generate` hook was removed in latest nuxt3 version.

They should add it back in coming days
https://github.com/nuxt/nuxt.js/issues/13701

**Comment by fiamma06** [comment]
Do it have temporary solution?

**Comment by benoitdemaegdt** [comment]
A Pull Request was opened few days ago.

I guess it should fix this issue once merged

https://github.com/nuxt/framework/pull/4304

**Comment by benoitdemaegdt** [comment]
Hey there 👋 

It should be fixed now.
Please copy paste the lastest version of sitemap.ts.

Then run 
`npm run dev`
And you should be able to access the sitemap at this url : `http://localhost:3000/sitemap.xml`

**Comment by todaynogada** [comment]
good!!!
thank you!!!
