### ISSUE TITLE
static page generation

### ISSUE THREAD

**Issue by codeflorist** [benoitdemaegdt/nuxt3-sitemap#3]
if you want to support static site genreation also, this would be the code for it:

```js
nuxt.hook('nitro:build:before', (nitro: Nitro) => {
	const paths = []
	nitro.hooks.hook('prerender:route', (route: PrerenderRoute) => {
		paths.push(route.route)
	})
	nitro.hooks.hook('close', async () => {
		const sitemap = await generateSitemap(paths)
		createSitemapFile(sitemap, filePath)
	})
})
```

of course the output-path should then be something like `.output/public/sitemap.xml`

**Comment by benoitdemaegdt** [comment]
Hey @codeflorist 👋 

Thank you for this piece of code. It works great !

I added a section for generating sitemap for prerendered sites powered by @nuxt/content.
👉  https://github.com/benoitdemaegdt/nuxt3-sitemap#setup-for-a-dynamic-site-powered-by-nuxtcontent-with-prerendering

Also, I gave you credit for this at the end of instruction 😉
