### ISSUE TITLE
how to solve incompatibility issues on nuxt 3.0.0-rc.10?

### ISSUE THREAD

**Issue by tsulatsitamim** [benoitdemaegdt/nuxt3-sitemap#5]
Module sitemap is disabled due to incompatibility issues.
Nuxt version `^3.0.0` is required but currently using `3.0.0-rc.10`

**Comment by benoitdemaegdt** [comment]
On this line, replace `^3.0.0` by `3.0.0-rc.10`
https://github.com/benoitdemaegdt/nuxt3-sitemap/blob/main/sitemap.ts#L12

**Comment by tsulatsitamim** [comment]
thank you
