### ISSUE TITLE
Addition of lastmod, changefreq and priority

### ISSUE THREAD

**Issue by BenjaminOddou** [benoitdemaegdt/nuxt3-sitemap#8]
Hello 👋,

is it possible to add the following tags like `lastmod`, `changefreq` and `priority`?
```xml
<url>
<loc>link</loc>
<lastmod>2022-08-12T15:19:11Z</lastmod>
<changefreq>weekly</changefreq>
<priority>0.8</priority>
</url>
```

**Comment by benoitdemaegdt** [comment]
Hey @BenjaminOddou 

This is currently not possible using this tutorial.
I do not plan to add this feature.

However, here is another way to generate a sitemap for nuxt3 and nuxt content that may help you :
https://content.nuxtjs.org/guide/recipes/sitemap

**Comment by benoitdemaegdt** [comment]
Hey @BenjaminOddou  👋 

I tried this new way of rendering a sitemap this morning.
I added [some documentation](https://github.com/benoitdemaegdt/nuxt3-sitemap#setup-for-a-dynamic-site-powered-by-nuxtcontent-with-prerendering) about it in the README.md.

I think you should be able to easily add `priority` in your sitemap.
You can add `priority: 0.8` in the front-matter block of your md files, and then edit the code to insert it in your sitemap
```
  for (const doc of docs) {
    sitemap.write({ url: doc._path, changefreq: 'monthly', priority: doc.priority || 0.5 })
  }
```

I hope it can help 🙌

**Comment by BenjaminOddou** [comment]
Hey @benoitdemaegdt, thank you for the info. Is nuxt/content required for this ? I am using the basic version of the module and I am not sure how to implement 🧐

**Comment by benoitdemaegdt** [comment]
Do you have dynamic pages ? Or only static ones ?
If you only have static pages you can create your sitemap manually.
Ex `sitemap.xml.ts` 👇 
```
export default defineEventHandler(async (event) => {
  const sitemap = new SitemapStream({ hostname: BASE_URL })

 const endpoints = [
  { endpoint: '/your-first-endpoint', changefreq: 'monthly', priority: 0.8 },
  { endpoint: '/your-second-endpoint', changefreq: 'monthly', priority: 0.7 },
  { endpoint: '/your-third-endpoint', changefreq: 'monthly', priority: 0.9 },
]

  for (const endpoint of endpoints) {
    sitemap.write({ url: endpoint.endpoint, changefreq: endpoint.changefreq, priority: endpoint.priority })
  }

  sitemap.end()
  return streamToPromise(sitemap)
})
```

**Comment by BenjaminOddou** [comment]
Hey @benoitdemaegdt, thank you for the feedback! I will plan to have some dynamic pages in my website. What could be a solution for that 🧐?

**Comment by benoitdemaegdt** [comment]
It depends on what you want to create.
There are quite a lot of CMS out there each having their pros and cons ...
[@nuxt/content](https://content.nuxtjs.org/) may be a good start if your looking for an easy and free way to add dynamic pages 😉 

Good luck with your project 🤞 
I'm closing this issue as there isn't much more to discuss here 😉
